M48
; DRILL file {KiCad 7.0.1} date Wed 24 May 2023 04:10:50 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-24T16:10:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.1339Y-4.1339
X4.1339Y-5.7087
X7.0866Y-4.1339
X7.0866Y-5.7087
T0
M30
